name: Item price compare

on: [push]

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 8
      uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - name: Cache NPM dependencies
      uses: actions/cache@v1
      with:
        path: what-to-flip/node_modules
        key: ${{ runner.OS }}-what-to-flip-${{ hashFiles('**/what-to-flip/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-what-to-flip-
    - name: Install NPM dependencies
      run: cd what-to-flip && yarn install
    - name: Lint
      run: cd what-to-flip && yarn lint

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 8
      uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - name: Cache NPM dependencies
      uses: actions/cache@v1
      with:
        path: what-to-flip/node_modules
        key: ${{ runner.OS }}-what-to-flip-${{ hashFiles('**/what-to-flip/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-what-to-flip-
    - name: Install NPM dependencies
      run: cd what-to-flip && yarn install
    - name: Build
      run: cd what-to-flip && yarn build
